# Generated by Django 5.1.6 on 2025-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="url_image",
            field=models.ImageField(max_length=500, upload_to="upload/url"),
        ),
    ]
