# Generated by Django 5.1.6 on 2025-04-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_alter_content_url_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="font_info",
            field=models.CharField(
                blank=True, default=None, max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="font_name",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
